// list of cache ids used in the application
export const CACHE_IDS = {
  CITIES: "wv-cities-cache",
  PINCODES_CITY: (cityId: string) => `wv-pincodes-city-cache-${cityId}`,
  AREA_CITY_PINCODE: (cityId: string, pincode: string) => `wv-area-cache-${cityId}-${pincode}`,
  CATEGORIES_AREA: (areaId: string) => `wv-categories-cache-${areaId}`,
  CATEGORY_SUMMARY_AREA: (areaId: string) => `wv-category-summary-cache-${areaId}`,
  PRODUCTS_AREA_CATEGORY: (areaId: string, categoryId: string) => `wv-products-category-cache-${areaId}-${categoryId}`,
  PRODUCT_AREA_PRODUCT_ID: (areaId: string, productId: string) => `wv-product-area-cache-${areaId}-${productId}`,  
  PRODUCTS_SEASONAL_AREA: (areaId: string) => `wv-products-seasonal-area-cache-${areaId}`,
  PRODUCTS_SEASONAL_AREA_CATEGORY: (areaId: string, categoryId: string) => `wv-products-seasonal-category-cache-${areaId}-${categoryId}`,
  PRODUCT_DETAILS_AREA_PRODUCT_ID: (areaId: string, productId: string) => `wv-product-details-area-cache-${areaId}-${productId}`,
  PRODUCTS_ALL_AREA: (areaId: string) => `wv-products-all-area-cache-${areaId}`,
  PRODUCTS_TAG_AREA_TAG: (areaId: string, tag: string) => `wv-products-tag-area-cache-${areaId}-${tag}`,
  PRODUCT_SEARCH_AREA_KEYWORD: (areaId: string, searchKeyword: string) => `wv-product-search-area-cache-${areaId}-${searchKeyword}`,
  PRODUCTS_SUBSCRIBABLE_AREA: (areaId: string) => `wv-products-subscribable-area-cache-${areaId}`,
  PRODUCTS_SUBSCRIBABLE_AREA_CATEGORY: (areaId: string, categoryId: string) => `wv-products-subscribable-category-cache-${areaId}-${categoryId}`,
  USER_RECENT_VISITED_PRODUCTS: (userId: string) => `wv-user-recent-visited-products-cache-${userId}`,
  ORDERS_RECENT_USER: (userId: string) => `wv-orders-recent-user-cache-${userId}`,
  ORDER_DETAILS_USER_ORDER_ID: (userId: string, orderId: string) => `wv-order-details-user-cache-${userId}-${orderId}`,
};
